### ISSUE TITLE
Upgrade to work with React 16

### ISSUE THREAD

**Issue by radufarcas10** [raulmatei/frux#1]
Hi @raulmatei ,

I don't know if this is still a WIP or not, but I'll try anyway. Would you please upgrade the lib to use React 16? I think only changing the import of `propTypes` from `prop-types` npm package instead of the `react` lib should be enough. Not sure though.

Thank you!

**Comment by raulmatei** [comment]
Will do, but please also have in mind that this uses https://github.com/jordangarcia/nuclear-js-react-addons which also has to upgrade React 16+. There seems to be a PR https://github.com/jordangarcia/nuclear-js-react-addons/issues/23 which is not yet merged. Also see: https://github.com/jordangarcia/nuclear-js-react-addons/issues/22

**Comment by raulmatei** [comment]
Version 1.0.0 is on NPM https://www.npmjs.com/package/frux - tests are failing because of `nuclear-js-react-addons` dependency that is still using `PropTypes` from `React`.
